### ISSUE TITLE
[Feat] If possible, you can proxy celebrities imgs

### ISSUE THREAD

**Issue by eallion** [lizheming/dover#1]
Not necessary, but thanks.

**Comment by lizheming** [comment]
I haven't used celebrities, maybe you can tell me how to get the picture and I can help implement it

**Comment by eallion** [comment]
A rust API of douban:
- https://github.com/eallion/douban-api-rs/blob/master/src/api.rs#L238

**Comment by lizheming** [comment]
Done~ 

- https://dou.img.lithub.cc/celebrity/1041028.jpg
- https://dou.img.lithub.cc/celebrity/1274477.jpg

![](https://dou.img.lithub.cc/celebrity/1041028.jpg)

**Comment by eallion** [comment]
Great!
